/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as PlagiarismRouteImport } from './routes/plagiarism'
import { Route as NewRouteImport } from './routes/new'
import { Route as ExportRouteImport } from './routes/export'
import { Route as CoverStudioRouteImport } from './routes/cover-studio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsAiRouteImport } from './routes/settings.ai'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'
import { Route as BookBookIdReadRouteImport } from './routes/book.$bookId.read'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PlagiarismRoute = PlagiarismRouteImport.update({
  id: '/plagiarism',
  path: '/plagiarism',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverStudioRoute = CoverStudioRouteImport.update({
  id: '/cover-studio',
  path: '/cover-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdReadRoute = BookBookIdReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => BookBookIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cover-studio': typeof CoverStudioRoute
  '/export': typeof ExportRoute
  '/new': typeof NewRoute
  '/plagiarism': typeof PlagiarismRoute
  '/templates': typeof TemplatesRoute
  '/book/$bookId': typeof BookBookIdRouteWithChildren
  '/settings/ai': typeof SettingsAiRoute
  '/book/$bookId/read': typeof BookBookIdReadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cover-studio': typeof CoverStudioRoute
  '/export': typeof ExportRoute
  '/new': typeof NewRoute
  '/plagiarism': typeof PlagiarismRoute
  '/templates': typeof TemplatesRoute
  '/book/$bookId': typeof BookBookIdRouteWithChildren
  '/settings/ai': typeof SettingsAiRoute
  '/book/$bookId/read': typeof BookBookIdReadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cover-studio': typeof CoverStudioRoute
  '/export': typeof ExportRoute
  '/new': typeof NewRoute
  '/plagiarism': typeof PlagiarismRoute
  '/templates': typeof TemplatesRoute
  '/book/$bookId': typeof BookBookIdRouteWithChildren
  '/settings/ai': typeof SettingsAiRoute
  '/book/$bookId/read': typeof BookBookIdReadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cover-studio'
    | '/export'
    | '/new'
    | '/plagiarism'
    | '/templates'
    | '/book/$bookId'
    | '/settings/ai'
    | '/book/$bookId/read'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cover-studio'
    | '/export'
    | '/new'
    | '/plagiarism'
    | '/templates'
    | '/book/$bookId'
    | '/settings/ai'
    | '/book/$bookId/read'
  id:
    | '__root__'
    | '/'
    | '/cover-studio'
    | '/export'
    | '/new'
    | '/plagiarism'
    | '/templates'
    | '/book/$bookId'
    | '/settings/ai'
    | '/book/$bookId/read'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoverStudioRoute: typeof CoverStudioRoute
  ExportRoute: typeof ExportRoute
  NewRoute: typeof NewRoute
  PlagiarismRoute: typeof PlagiarismRoute
  TemplatesRoute: typeof TemplatesRoute
  BookBookIdRoute: typeof BookBookIdRouteWithChildren
  SettingsAiRoute: typeof SettingsAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plagiarism': {
      id: '/plagiarism'
      path: '/plagiarism'
      fullPath: '/plagiarism'
      preLoaderRoute: typeof PlagiarismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-studio': {
      id: '/cover-studio'
      path: '/cover-studio'
      fullPath: '/cover-studio'
      preLoaderRoute: typeof CoverStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId/read': {
      id: '/book/$bookId/read'
      path: '/read'
      fullPath: '/book/$bookId/read'
      preLoaderRoute: typeof BookBookIdReadRouteImport
      parentRoute: typeof BookBookIdRoute
    }
  }
}

interface BookBookIdRouteChildren {
  BookBookIdReadRoute: typeof BookBookIdReadRoute
}

const BookBookIdRouteChildren: BookBookIdRouteChildren = {
  BookBookIdReadRoute: BookBookIdReadRoute,
}

const BookBookIdRouteWithChildren = BookBookIdRoute._addFileChildren(
  BookBookIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoverStudioRoute: CoverStudioRoute,
  ExportRoute: ExportRoute,
  NewRoute: NewRoute,
  PlagiarismRoute: PlagiarismRoute,
  TemplatesRoute: TemplatesRoute,
  BookBookIdRoute: BookBookIdRouteWithChildren,
  SettingsAiRoute: SettingsAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
